name: Deploy to S3

# Ejecuta el workflow en cada push al branch 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Chequea el repositorio en la máquina runner
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configura las credenciales de AWS usando los secretos
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Cambia la región según corresponda

      # Sube los archivos al bucket S3
      - name: Sync S3 Bucket
        run: |
          aws s3 sync . s3://vehiculos3mc --exclude ".git/*" --delete